spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect